controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_controllers:
    resource: ../src/Controller/Admin
    type: attribute
    prefix: /admin